-- PJM Long-Term Load Forecast — forecast-layer seed
-- Idempotent: vintages upsert on (source_id,vintage_label); observations delete-by-source then insert.
-- Executed against Supabase project ycadmmngkdhvpcsrcuaq. All values traced to cited sources (see notes).
begin;

insert into forecast_vintages (source_id,vintage_label,published_date,horizon_end_year,source_url,archive_url,notes) values ('pjm-long-term-load-forecast','2022 Load Forecast','2022-01-15',2037,'https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/','https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/','PJM annual Long-Term Load Forecast, 2022 vintage. Released January (exact day approximate). Publicly archived in the PJM load-forecast library.') on conflict (source_id,vintage_label) do update set published_date=excluded.published_date, horizon_end_year=excluded.horizon_end_year, source_url=excluded.source_url, archive_url=excluded.archive_url, notes=excluded.notes;
insert into forecast_vintages (source_id,vintage_label,published_date,horizon_end_year,source_url,archive_url,notes) values ('pjm-long-term-load-forecast','2023 Load Forecast','2023-01-15',2038,'https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/','https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/','PJM Long-Term Load Forecast, 2023 vintage. Released January (approx). Recoverable via PJM load-forecast library. No headline DOM-2037 data-center datapoint cleanly published for this vintage (see PR report).') on conflict (source_id,vintage_label) do update set published_date=excluded.published_date, horizon_end_year=excluded.horizon_end_year, source_url=excluded.source_url, archive_url=excluded.archive_url, notes=excluded.notes;
insert into forecast_vintages (source_id,vintage_label,published_date,horizon_end_year,source_url,archive_url,notes) values ('pjm-long-term-load-forecast','2024 Load Forecast','2024-01-15',2039,'https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/','https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/','PJM Long-Term Load Forecast, 2024 vintage. Released January (approx). Recoverable via PJM library. No cleanly-published DOM-2037 DC datapoint located (see PR report).') on conflict (source_id,vintage_label) do update set published_date=excluded.published_date, horizon_end_year=excluded.horizon_end_year, source_url=excluded.source_url, archive_url=excluded.archive_url, notes=excluded.notes;
insert into forecast_vintages (source_id,vintage_label,published_date,horizon_end_year,source_url,archive_url,notes) values ('pjm-long-term-load-forecast','2025 Load Forecast','2025-01-15',2045,'https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/2025-load-report.pdf','https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/','PJM 2025 Long-Term Load Forecast Report (extended to 20-year horizon per FERC Order 1920). Released January 2025 (exact day approximate).') on conflict (source_id,vintage_label) do update set published_date=excluded.published_date, horizon_end_year=excluded.horizon_end_year, source_url=excluded.source_url, archive_url=excluded.archive_url, notes=excluded.notes;
delete from forecast_observations where source_id='pjm-long-term-load-forecast' and method='manual';
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='pjm-long-term-load-forecast' and vintage_label='2022 Load Forecast'),'pjm-long-term-load-forecast',null,'PWR-08',2037,'Dominion (DOM) zone data-center load',5700,'MW','base','reported','manual','PJM 2022 Long-Term Load Forecast: Dominion (DOM) zone data-center-driven load growth projected to ~5,700 MW by 2037. As reported by IEEFA (''Projected data center growth spurs PJM capacity prices by factor of 10'') and Amperon (''Why Virginia Data Centers Matter to All of PJM''), citing the 2022 PJM vintage; corroborated by the Faraday Forecast Source Registry. DOM zone spans many VA jurisdictions -> jurisdiction_id NULL (scope=iso-zone). Definitional note: 2022 figure framed as DOM-zone load growth by 2037.');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='pjm-long-term-load-forecast' and vintage_label='2025 Load Forecast'),'pjm-long-term-load-forecast',null,'PWR-08',2037,'Dominion (DOM) zone data-center load',20000,'MW','base','reported','manual','PJM 2025 Long-Term Load Forecast: Dominion (DOM) zone data-center load surpasses 20,000 MW by 2037. Stored as 20000 = published floor (''>20,000 MW''). Reported by IEEFA & Amperon citing the 2025 vintage; corroborated by registry. DOM zone -> jurisdiction_id NULL (scope=iso-zone). Canonical vintage-over-vintage revision vs 2022 (~5,700 MW).');
commit;
