-- Texas State Water Plan — forecast-layer seed
-- Idempotent: vintages upsert on (source_id,vintage_label); observations delete-by-source then insert.
-- Executed against Supabase project ycadmmngkdhvpcsrcuaq. All values traced to cited sources (see notes).
begin;

insert into forecast_vintages (source_id,vintage_label,published_date,horizon_end_year,source_url,archive_url,notes) values ('texas-state-water-plan','2022 State Water Plan','2021-07-07',2070,'https://www.twdb.texas.gov/waterplanning/swp/2022/index.asp','https://www.twdb.texas.gov/waterplanning/swp/','TWDB 2022 State Water Plan; adopted July 2021; covers 2020-2070; drought-of-record scenario; capital in 2018 dollars.') on conflict (source_id,vintage_label) do update set published_date=excluded.published_date, horizon_end_year=excluded.horizon_end_year, source_url=excluded.source_url, archive_url=excluded.archive_url, notes=excluded.notes;
insert into forecast_vintages (source_id,vintage_label,published_date,horizon_end_year,source_url,archive_url,notes) values ('texas-state-water-plan','Draft 2027 State Water Plan','2026-04-16',2080,'https://www.twdb.texas.gov/waterplanning/swp/2027/index.asp','https://www.twdb.texas.gov/waterplanning/swp/','TWDB Draft 2027 State Water Plan; Phase I draft published 2026-04-16; covers 2030-2080; capital in 2023 dollars.') on conflict (source_id,vintage_label) do update set published_date=excluded.published_date, horizon_end_year=excluded.horizon_end_year, source_url=excluded.source_url, archive_url=excluded.archive_url, notes=excluded.notes;
delete from forecast_observations where source_id='texas-state-water-plan' and method='manual';
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='texas-state-water-plan' and vintage_label='2022 State Water Plan'),'texas-state-water-plan',null,null,2070,'Statewide total recommended capital cost (whole-plan)',80,'billion USD','base','high','manual','2022 State Water Plan total capital cost to implement ~5,800 water management strategies across ~2,400 projects ~= $80 billion (2018 dollars); delivers 7.7 maf/yr additional supply by 2070. Source: TWDB 2022 State Water Plan (Financing Needs / Executive Summary), corroborated by TX Comptroller Fiscal Notes (Sep 2023). Whole-plan total; target_year=2070 is the common vintage-comparison anchor. Base year 2018$.');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='texas-state-water-plan' and vintage_label='Draft 2027 State Water Plan'),'texas-state-water-plan',null,null,2070,'Statewide total recommended capital cost (whole-plan)',174,'billion USD','base','high','manual','Draft 2027 State Water Plan total capital cost ~= $174 billion (2023 dollars) across ~6,700 strategies / ~3,000 projects; delivers up to 7.6 maf/yr by 2080. Source: TWDB Draft 2027 SWP (2026-04-16), as reported by Smart Water Magazine and Texas Scorecard; TWDB states this more than doubled the 2022 plan''s ~$81B. Whole-plan total; horizon extended 2070->2080. target_year=2070 used as common comparison anchor. CAVEAT: dollar-year (2023$ vs 2018$) and horizon (2080 vs 2070) differ from the 2022 vintage; delta is the plan-cycle headline comparison, not a like-for-like real-dollar delta.');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='texas-state-water-plan' and vintage_label='2022 State Water Plan'),'texas-state-water-plan',null,'WTR-01',2070,'Statewide water needs (unmet demand), drought-of-record',6.86,'million acre-feet/yr','drought-of-record','high','manual','2022 SWP: projected 2070 water needs (shortage) ~= 6.86 maf/yr under drought-of-record. Source: TWDB 2022 SWP; TX Comptroller Fiscal Notes (Sep 2023).');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='texas-state-water-plan' and vintage_label='Draft 2027 State Water Plan'),'texas-state-water-plan',null,'WTR-01',2080,'Statewide water needs (unmet demand), drought-of-record',5.8,'million acre-feet/yr','drought-of-record','medium','manual','Draft 2027 SWP: projected 2080 shortage ~= 5.8 maf/yr (~1/3 of total projected demand). Source: Smart Water Magazine citing TWDB Draft 2027 SWP.');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='texas-state-water-plan' and vintage_label='2022 State Water Plan'),'texas-state-water-plan',null,'WTR-02',2070,'Recommended additional water supply delivered',7.7,'million acre-feet/yr','base','high','manual','2022 SWP: recommended strategies add ~7.7 maf/yr of new supply by 2070. Source: TWDB 2022 SWP.');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='texas-state-water-plan' and vintage_label='Draft 2027 State Water Plan'),'texas-state-water-plan',null,'WTR-02',2080,'Recommended additional water supply delivered',7.6,'million acre-feet/yr','base','medium','manual','Draft 2027 SWP: recommended strategies deliver up to ~7.6 maf/yr by 2080. Source: TWDB Draft 2027 SWP via Smart Water Magazine.');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='texas-state-water-plan' and vintage_label='2022 State Water Plan'),'texas-state-water-plan',null,'WTR-02',2020,'Statewide existing water supply',16.8,'million acre-feet/yr','base','medium','manual','2022 SWP: existing water supply ~16.8 maf/yr in 2020. Source: Texas Real Estate Research Center / TWDB 2022 SWP.');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='texas-state-water-plan' and vintage_label='2022 State Water Plan'),'texas-state-water-plan',null,'WTR-02',2070,'Statewide existing water supply',13.8,'million acre-feet/yr','base','medium','manual','2022 SWP: existing water supply projected to decline to ~13.8 maf/yr by 2070. Source: Texas Real Estate Research Center / TWDB 2022 SWP.');
commit;
