-- EIA Annual Energy Outlook (AEO) — forecast-layer seed
-- Idempotent: vintages upsert on (source_id,vintage_label); observations delete-by-source then insert.
-- Executed against Supabase project ycadmmngkdhvpcsrcuaq. All values traced to cited sources (see notes).
begin;

insert into forecast_vintages (source_id,vintage_label,published_date,horizon_end_year,source_url,archive_url,notes) values ('eia-annual-energy-outlook-aeo','AEO2023','2023-03-16',2050,'https://www.eia.gov/outlooks/aeo/','https://www.eia.gov/outlooks/aeo/archive.php','EIA Annual Energy Outlook 2023 (released 2023-03-16). Vintage row seeded for lineage; per-year electricity totals across cases require the EIA API / AEO Table Browser (Myke gate: EIA_API_KEY) and were not machine-extractable here (see PR report).') on conflict (source_id,vintage_label) do update set published_date=excluded.published_date, horizon_end_year=excluded.horizon_end_year, source_url=excluded.source_url, archive_url=excluded.archive_url, notes=excluded.notes;
insert into forecast_vintages (source_id,vintage_label,published_date,horizon_end_year,source_url,archive_url,notes) values ('eia-annual-energy-outlook-aeo','AEO2025','2025-04-15',2050,'https://www.eia.gov/outlooks/aeo/','https://www.eia.gov/outlooks/aeo/archive.php','EIA Annual Energy Outlook 2025 (released April 2025; exact day approximate). Reference + alternative cases to 2050.') on conflict (source_id,vintage_label) do update set published_date=excluded.published_date, horizon_end_year=excluded.horizon_end_year, source_url=excluded.source_url, archive_url=excluded.archive_url, notes=excluded.notes;
delete from forecast_observations where source_id='eia-annual-energy-outlook-aeo' and method='manual';
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='eia-annual-energy-outlook-aeo' and vintage_label='AEO2025'),'eia-annual-energy-outlook-aeo',null,'PWR-07',2050,'Total U.S. electricity consumption',6646.17,'TWh','reference','medium','manual','AEO2025 Reference case: total U.S. electricity consumption ~= 6,646.17 TWh by 2050. Source: RBAC review of EIA AEO2025 (citing the AEO2025 data browser). Corroborated by EIA AEO2025 (~50% rise to ~6,000 TWh generation by 2050).');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='eia-annual-energy-outlook-aeo' and vintage_label='AEO2025'),'eia-annual-energy-outlook-aeo',null,'PWR-08',2024,'Commercial computing share of commercial-sector electricity',8,'%','reference','medium','manual','AEO2025 Reference: commercial computing (incl. data-center servers) = 8% of commercial-sector electricity in 2024. Source: EIA Today in Energy id=65564 (''Electricity use for commercial computing could surpass space cooling, ventilation'').');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='eia-annual-energy-outlook-aeo' and vintage_label='AEO2025'),'eia-annual-energy-outlook-aeo',null,'PWR-08',2050,'Commercial computing share of commercial-sector electricity',20,'%','reference','medium','manual','AEO2025 Reference: commercial computing grows to 20% of commercial-sector electricity by 2050. Source: EIA Today in Energy id=65564.');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='eia-annual-energy-outlook-aeo' and vintage_label='AEO2025'),'eia-annual-energy-outlook-aeo',null,'PWR-08',2050,'Commercial-sector server electricity consumption',446,'billion kWh','reference','medium','manual','EIA, ''Data center server energy use grows across the commercial building stock'' (Today in Energy id=67704): commercial-sector server consumption reaches 446 BkWh (lower/reference) to 818 BkWh (High Electricity Demand) by 2050. This row = lower/reference case. AEO vintage per that EIA article; confidence medium (see PR note on AEO-year attribution).');
insert into forecast_observations (vintage_id,source_id,jurisdiction_id,attribute_code,target_year,metric_name,value,unit,scenario,confidence,method,notes) values ((select vintage_id from forecast_vintages where source_id='eia-annual-energy-outlook-aeo' and vintage_label='AEO2025'),'eia-annual-energy-outlook-aeo',null,'PWR-08',2050,'Commercial-sector server electricity consumption',818,'billion kWh','high electricity demand','medium','manual','EIA Today in Energy id=67704: commercial-sector server consumption reaches 818 BkWh by 2050 in the High Electricity Demand case (vs 446 BkWh lower case). Confidence medium (AEO-year attribution per EIA article).');
commit;
