-- 0031_far418_source_expansion.sql
--
-- CC-BOUNDSTONE-INGEST-1.1 §7 (FAR-418) — source expansion to NATIONAL
-- COMPLETENESS. GENERATED by scripts/far418-gen-source-expansion.mjs from
-- scripts/far418-rosters.mjs. Do not hand-edit; edit the roster and re-run.
--
-- ⚠️ UN-APPLIED. No production seed is authorized by this CC (§2).
--
-- WHY COMPLETENESS BEFORE TUNING (§7, §12): 26 of 51 commissions is not
-- "commissions covered", it is a map with holes that reads as quiet states.
-- Every class below is registered for all of its members in one go, and no
-- member is tuned until the class is whole.
--
-- NOTHING HERE ACTIVATES ANYTHING. Every row lands status='registered'.
-- Activation is `source-poller verify`'s job and happens only for a source
-- whose feed actually resolved. A URL we could not confirm therefore fails
-- loudly (status='error', reported by the §8 staleness monitor) instead of
-- sitting in the registry looking like coverage.
--
-- URL PROVENANCE: fetch_config.url_provenance='pattern' marks an endpoint
-- derived from the dominant naming convention and NOT yet probed. That is the
-- honest state of the 51 governor rows at authoring time. See
-- docs/far-418/source-expansion-report.md for the count and the follow-up.

begin;

create temporary table far418_states (abbr text primary key, name text, gov_host text) on commit drop;
insert into far418_states (abbr, name, gov_host) values
    ('AL', 'Alabama', 'governor.alabama.gov'),
    ('AK', 'Alaska', 'gov.alaska.gov'),
    ('AZ', 'Arizona', 'azgovernor.gov'),
    ('AR', 'Arkansas', 'governor.arkansas.gov'),
    ('CA', 'California', 'www.gov.ca.gov'),
    ('CO', 'Colorado', 'www.colorado.gov/governor'),
    ('CT', 'Connecticut', 'portal.ct.gov/office-of-the-governor'),
    ('DE', 'Delaware', 'governor.delaware.gov'),
    ('DC', 'District of Columbia', 'mayor.dc.gov'),
    ('FL', 'Florida', 'www.flgov.com'),
    ('GA', 'Georgia', 'gov.georgia.gov'),
    ('HI', 'Hawaii', 'governor.hawaii.gov'),
    ('ID', 'Idaho', 'gov.idaho.gov'),
    ('IL', 'Illinois', 'www.illinois.gov/government/executive-branch/governor'),
    ('IN', 'Indiana', 'www.in.gov/gov'),
    ('IA', 'Iowa', 'governor.iowa.gov'),
    ('KS', 'Kansas', 'governor.kansas.gov'),
    ('KY', 'Kentucky', 'www.kentucky.gov/Pages/governor.aspx'),
    ('LA', 'Louisiana', 'gov.louisiana.gov'),
    ('ME', 'Maine', 'www.maine.gov/governor'),
    ('MD', 'Maryland', 'governor.maryland.gov'),
    ('MA', 'Massachusetts', 'www.mass.gov/orgs/office-of-the-governor'),
    ('MI', 'Michigan', 'www.michigan.gov/whitmer'),
    ('MN', 'Minnesota', 'mn.gov/governor'),
    ('MS', 'Mississippi', 'governorreeves.ms.gov'),
    ('MO', 'Missouri', 'governor.mo.gov'),
    ('MT', 'Montana', 'governor.mt.gov'),
    ('NE', 'Nebraska', 'governor.nebraska.gov'),
    ('NV', 'Nevada', 'gov.nv.gov'),
    ('NH', 'New Hampshire', 'www.governor.nh.gov'),
    ('NJ', 'New Jersey', 'www.nj.gov/governor'),
    ('NM', 'New Mexico', 'www.governor.state.nm.us'),
    ('NY', 'New York', 'www.governor.ny.gov'),
    ('NC', 'North Carolina', 'governor.nc.gov'),
    ('ND', 'North Dakota', 'www.governor.nd.gov'),
    ('OH', 'Ohio', 'governor.ohio.gov'),
    ('OK', 'Oklahoma', 'oklahoma.gov/governor.html'),
    ('OR', 'Oregon', 'www.oregon.gov/gov'),
    ('PA', 'Pennsylvania', 'www.pa.gov/governor'),
    ('RI', 'Rhode Island', 'governor.ri.gov'),
    ('SC', 'South Carolina', 'governor.sc.gov'),
    ('SD', 'South Dakota', 'governor.sd.gov'),
    ('TN', 'Tennessee', 'www.tn.gov/governor'),
    ('TX', 'Texas', 'gov.texas.gov'),
    ('UT', 'Utah', 'governor.utah.gov'),
    ('VT', 'Vermont', 'governor.vermont.gov'),
    ('VA', 'Virginia', 'www.governor.virginia.gov'),
    ('WA', 'Washington', 'governor.wa.gov'),
    ('WV', 'West Virginia', 'governor.wv.gov'),
    ('WI', 'Wisconsin', 'evers.wi.gov'),
    ('WY', 'Wyoming', 'governor.wyo.gov');

create temporary table far418_markets (key text primary key, name text, domain text, notices_path text, queue_key text) on commit drop;
insert into far418_markets (key, name, domain, notices_path, queue_key) values
    ('caiso', 'California ISO', 'caiso.com', '/informed/Pages/Notifications/Default.aspx', null),
    ('ercot', 'Electric Reliability Council of Texas', 'ercot.com', '/services/comm/mkt_notices', 'iso:ercot-gis'),
    ('isone', 'ISO New England', 'iso-ne.com', '/participate/participant-readiness/', null),
    ('miso', 'Midcontinent ISO', 'misoenergy.org', '/markets-and-operations/communications/', 'iso:miso-queue'),
    ('nyiso', 'New York ISO', 'nyiso.com', '/market-notices', null),
    ('pjm', 'PJM Interconnection', 'pjm.com', '/markets-and-operations/etools/oasis/system-information', 'iso:pjm-queue'),
    ('spp', 'Southwest Power Pool', 'spp.org', '/news-list/', null);

-- ---------------------------------------------------------------------------
-- §7.1 GOVERNORS — 51 rows, gov:<state>. Currently ZERO exist: governors are
-- not monitored at all, which is why a state executive directive halting
-- approvals could not be seen by any lane.
-- ---------------------------------------------------------------------------
insert into source_registry (
  source_key, name, provider, url, feed_url, access_method, cadence, confidence_cap,
  license, license_status, idf_domains, scope, countable, status, subsystem, fetcher,
  source_type, fetch_config
)
select
  'gov:' || lower(s.abbr),
  left(s.name || ' — Governor''s office newsroom', 200),
  s.name || ' executive branch',
  'https://' || s.gov_host,
  null,
  'rss',                       -- verify downgrades to 'html' index-poll when no feed exists
  'daily',
  'SRC',
  'Official state government publication',
  'cleared',                   -- §7.1: official state publications
  array[]::text[],             -- Boundstone never reads these (Decision 2); empty, not guessed
  null,
  false,
  'registered',
  'poller',
  'source-poller',
  'government_feed',
  jsonb_build_object(
    'far418', true, 'source_class', 'governor', 'state_abbr', s.abbr,
    'url_provenance', 'pattern',
    'note', 'Governor newsroom / executive-order index. Registered, NOT activated: source-poller verify must resolve a feed or a usable index before this can produce.'
  )
from far418_states s
where not exists (select 1 from source_registry r where r.source_key = 'gov:' || lower(s.abbr));

-- ---------------------------------------------------------------------------
-- §7.2 COMMISSIONS — complete the 51 and clear the licence on all of them.
--
-- 26 rows existed, 2 active, 24 had never produced. The missing 25 states + DC
-- are computed here rather than listed, so this is correct whatever has been
-- added since it was written.
--
-- The URL is the state's own portal, which we do not know for the missing
-- jurisdictions — so these rows are registered with an EMPTY url and left for
-- the portal-family adapter work (§7.2) to fill. An empty url cannot be probed
-- and cannot be activated, which is the correct behaviour: registering a
-- guessed commission portal would be worse than registering none.
--
-- Empty string, not NULL: source_registry.url is NOT NULL DEFAULT ''. Writing
-- NULL here would abort the migration on a not-null violation. '' is the
-- column's own idiom for "unset" and behaves identically downstream —
-- discoverCandidates() returns no candidates for it, so verify fails the row
-- cleanly into status='error' rather than probing something arbitrary.
-- ---------------------------------------------------------------------------
insert into source_registry (
  source_key, name, provider, url, feed_url, access_method, cadence, confidence_cap,
  license, license_status, idf_domains, scope, countable, status, subsystem, fetcher,
  source_type, fetch_config
)
select
  'puc:' || lower(s.abbr),
  left(s.name || ' — utility commission dockets', 200),
  s.name || ' utility commission',
  '',                          -- NOT NULL DEFAULT ''; see the note above
  null,
  'html',
  'weekly',
  'SRC',
  'Official state government publication',
  'cleared',                   -- Decision 4: all PUCs are legitimate, quotable sources
  array[]::text[],
  'us-state',
  false,
  'registered',
  'puc',
  'source-poller',
  'government_feed',
  jsonb_build_object(
    'far418', true, 'source_class', 'puc', 'state_abbr', s.abbr,
    'url_provenance', 'unresolved',
    'query_terms', '["data center","large load","interconnection","load interconnection"]'::jsonb,
    'note', 'Docket portal URL not yet resolved. Registered so the gap is COUNTED rather than invisible — 25 unregistered states read as quiet states. Blocked on the portal-family adapter pass (§7.2).'
  )
from far418_states s
where not exists (select 1 from source_registry r where r.source_key = 'puc:' || lower(s.abbr));

-- Decision 4 applied to every commission row that already existed, including
-- the puc:dockets pilot which has sat 'unreviewed' and has never run.
update source_registry
   set license_status = 'cleared',
       updated_at = now(),
       fetch_config = coalesce(fetch_config, '{}'::jsonb)
         || jsonb_build_object('far418_license_cleared', 'CC-BOUNDSTONE-INGEST-1.1 Decision 4')
 where source_key like 'puc:%' and license_status <> 'cleared';

-- §7.2 final bullet: clear every puc:* row currently in error so the class gets
-- one clean verify pass. Failures after that are real and will be reported.
update source_registry
   set status = 'registered',
       consecutive_failures = 0,
       updated_at = now(),
       fetch_config = coalesce(fetch_config, '{}'::jsonb)
         || jsonb_build_object('far418_error_cleared_at', now())
 where source_key like 'puc:%' and status = 'error';

-- ---------------------------------------------------------------------------
-- §7.3 MARKET OPERATORS — 7 organizations, two lanes each, 14 rows.
--
-- Today 3 rows exist and ALL THREE are generation-queue data products. Not one
-- notices lane produces anything, which is how a market-operator protocol
-- revision gating large-load interconnection reached nobody.
-- ---------------------------------------------------------------------------

-- Lane A: notices. The new capability.
insert into source_registry (
  source_key, name, provider, url, feed_url, access_method, cadence, confidence_cap,
  license, license_status, idf_domains, scope, countable, status, subsystem, fetcher,
  source_type, fetch_config
)
select
  'iso:' || m.key || '-notices',
  left(m.name || ' — market notices and protocol revisions', 200),
  m.name,
  'https://www.' || m.domain || m.notices_path,
  null,
  'rss',                       -- most publish no RSS; verify falls back to index-poll
  'daily',
  'SRC',
  'Market operator publication — quotable under CC-BOUNDSTONE-INGEST-1.1 Decision 4',
  'cleared',
  array[]::text[],
  null,
  false,
  'registered',
  'poller',
  'source-poller',
  'industry_entity',
  jsonb_build_object(
    'far418', true, 'source_class', 'iso_rto', 'market_key', m.key,
    'url_provenance', 'pattern',
    'note', 'Market notices index. These organisations are private corporations: none passes the government-TLD test, and all seven are on boundstone.allowed_source_domains.'
  )
from far418_markets m
where not exists (select 1 from source_registry r where r.source_key = 'iso:' || m.key || '-notices');

-- Lane B: the interconnection-queue data product, where one exists. For the
-- three already registered this is a LICENCE CORRECTION only (unreviewed →
-- cleared, Decision 4); the other four are registered fresh.
update source_registry
   set license_status = 'cleared',
       updated_at = now(),
       fetch_config = coalesce(fetch_config, '{}'::jsonb)
         || jsonb_build_object('far418_license_cleared', 'CC-BOUNDSTONE-INGEST-1.1 Decision 4',
                               'source_class', 'iso_rto')
 where source_key like 'iso:%' and license_status <> 'cleared';

-- ---------------------------------------------------------------------------
-- §7.4 UTILITIES — Phase 1 ([REC-4]) is NOT SEEDED HERE, deliberately.
--
-- The roster is real and available: eia_utility_territories holds 145 distinct
-- investor-owned utilities for report_year 2024 (the CC estimates ~180; 145 is
-- the measured figure, and a further 1,687 utility_ids carry a NULL
-- ownership_type and are therefore unclassifiable from this table alone).
--
-- What is missing is the one thing a source row cannot do without: the
-- utility's own domain. There is no domain for any of the 145 anywhere in the
-- stack — a join against public.companies.website_url matches 0 of 145. Every
-- available path to a URL here is a guess, and a guessed utility domain that
-- happens to resolve is worse than no row at all.
--
-- So Phase 1 is reported as blocked on a domain-resolution pass rather than
-- seeded with invented endpoints. The delta is in
-- docs/far-418/source-expansion-report.md. Phase 2 (co-ops and municipals
-- intersecting a county that already holds a Boundstone record) was spec'd, not
-- built, by the CC itself.
-- ---------------------------------------------------------------------------

do $post$
declare govs int; pucs int; isos int;
begin
  select count(*) into govs from source_registry where source_key like 'gov:%';
  select count(*) into pucs from source_registry where source_key like 'puc:%' and scope = 'us-state';
  select count(*) into isos from source_registry where source_key like 'iso:%';
  if govs <> 51 then raise exception 'ABORT: expected 51 governor rows, got %', govs; end if;
  if pucs <> 51 then raise exception 'ABORT: expected 51 state commission rows, got %', pucs; end if;
  if isos < 11 then raise exception 'ABORT: expected at least 11 market-operator rows (7 notices + >=4 queue), got %', isos; end if;
  if exists (select 1 from source_registry where source_key like 'puc:%' and license_status <> 'cleared') then
    raise exception 'ABORT: a commission row is not licence-cleared — Decision 4 not honoured';
  end if;
  if exists (select 1 from source_registry
             where (source_key like 'gov:%' or source_key like 'iso:%' or source_key like 'puc:%')
               and status = 'active' and last_ok_at is null) then
    raise exception 'ABORT: a row was activated without a successful probe';
  end if;
  raise notice 'FAR-418 0031: % governors, % commissions, % market-operator lanes registered. None activated.', govs, pucs, isos;
end
$post$;

commit;
